name: Markbase
description: A database-oriented notes app.

version: 1.0.0+3

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.4.6
  cloud_functions: ^3.3.3
  crypto: ^3.0.2
  cupertino_icons: ^1.0.2
  firebase_analytics: ^9.3.7
  firebase_app_check: ^0.0.8
  firebase_auth: ^3.6.2
  firebase_core: ^1.21.1
  firebase_crashlytics: ^2.8.12
  firebase_performance: ^0.8.3+2
  firebase_remote_config: ^2.0.16
  firebase_storage: ^10.3.4
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  flutter_svg: ^1.0.3
  flutter_vibrate: ^1.3.0
  get_storage: ^2.0.3
  google_sign_in: ^5.4.2
  image_picker: ^0.8.5+3
  in_app_review: ^2.0.4
  lottie: ^1.4.3
  package_info_plus: ^1.4.3+1
  permission_handler: ^10.0.1
  sign_in_with_apple: ^3.3.0
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_launcher_icons: "^0.10.0"
  flutter_lints: ^1.0.0
  flutter_native_splash: ^2.2.9
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/logos/
    - assets/lottie/

  uses-material-design: true

  # There is an issue with the documented way of adding custom fonts, this is a workaround
  fonts:
    - family: Light
      fonts:
        - asset: assets/fonts/Gilroy-Light.ttf

    - family: Regular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf

    - family: Medium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf

    - family: SemiBold
      fonts:
        - asset: assets/fonts/Gilroy-SemiBold.ttf

    - family: Bold
      fonts:
        - asset: assets/fonts/Gilroy-Bold.ttf

    - family: ExtraBold
      fonts:
        - asset: assets/fonts/Gilroy-ExtraBold.ttf

    - family: Black
      fonts:
        - asset: assets/fonts/Gilroy-Black.ttf

# Icon (generated)
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/markbase-app-icon.png"

# Splash screen (generated)
flutter_native_splash:
  color: "#ffffff"
  image: "assets/logos/markbase-full-logo-black.png"

  color_dark: "#000000"
  image_dark: "assets/logos/markbase-full-logo-white.png"
