// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDSm7Ds6qEuhsrrANydfFyMoxEFAJaRPY',
    appId: '1:431481614037:android:8def2eb59a5ab2dd4f7c5c',
    messagingSenderId: '431481614037',
    projectId: 'markbase-dev',
    databaseURL: 'https://markbase-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'markbase-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0-Jzn960vAzPDy_kkqbSKMJ5dC8na9FA',
    appId: '1:431481614037:ios:b376fc5c5fe515b14f7c5c',
    messagingSenderId: '431481614037',
    projectId: 'markbase-dev',
    databaseURL: 'https://markbase-dev-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'markbase-dev.appspot.com',
    iosClientId: '431481614037-uacotokmqqtrkkdic2mfaqm4iol7pm9e.apps.googleusercontent.com',
    iosBundleId: 'se.markba.markbase',
  );
}
